### ISSUE TITLE
Relation between /h#change-n and /patches/n/ ?

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-server#100]
(I almost wrote `/h#patch-n`, but all the information related to `/patches/n/` is basically related to `h#change-n`, except for the URL of the jsonpatch resource).

The representation of the latter includes a few things that are not in the main history graph:

  * comments (this could easily be representable in RDF, and maybe should be included in the main history graph)

  * The status of the patch and whether it is able to be merged

  * A map of identifiers minted from skolem IDs

Can we add a link between the two corresponding resources for a change/patch? Probably `rdfs:seeAlso`. It will always exist from A->B, but not always from B->A (Since there is the case where a patch has not yet or was not merged).

**Comment by rybesh** [comment]
OK, I added a relation from each change to its corresponding patch request, e.g.:

```turtle
<https://staging.perio.do/h#change-42>
    rdfs:seeAlso <https://staging.perio.do/h#patch-request-42> .
<https://staging.perio.do/h#patch-request-42>
    foaf:page <https://staging.perio.do/patches/42/> .
```

I wasn't sure what you meant about the reverse link (from the patch request to the change). We currently don't serve a JSON-LD representation of a patch request; it's just plain JSON. 

I also added comments to the history, using the [Activity Streams](https://www.w3.org/TR/activitystreams-core/) vocabulary:

```turtle
<https://staging.perio.do/h#patch-request-42>
    as:replies <https://staging.perio.do/h#patch-request-42-comments> .
<https://staging.perio.do/h#patch-request-42-comments>
    as:totalItems "2"^^xsd:nonNegativeInteger ;
    as:first <https://staging.perio.do/h#patch-request-42-comment-16> ;
    as:last <https://staging.perio.do/h#patch-request-42-comment-17> ;
    as:items
        <https://staging.perio.do/h#patch-request-42-comment-16>,
        <https://staging.perio.do/h#patch-request-42-comment-17> .
<https://staging.perio.do/h#patch-request-42-comment-16>
    a as:Note ;
    as:attributedTo <https://orcid.org/0000-0003-2557-5145> ;
    as:published "2016-04-24T12:59:40+00:00"^^xsd:dateTime ;
    as:mediaType "text/plain" ;
    as:content "Collection generated in JSON independent of PeriodO client interface, in close collaboration between Lyman and PeriodO team. First externally-generated JSON document merged into the Canonical PeriodO dataset." .
```

See the [updated context] for how the AS terms are mapped to JSON keys.

**Comment by ptgolden** [comment]
Perfect! Thanks.
