### ISSUE TITLE
Add activitystream predicates to context

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-server#123]
In the history json file, every external namespaced URL is abbreviated except for the `activitystream` ones. (Which all have to do with comments on patch requests, I believe).

Here's a list of them:
`activity:attributedTo`
`activity:content`
`activity:first`
`activity:items`
`activity:last`
`activity:mediaType`
`activity:Note`
`activity:published`
`activity:replies`
`activity:totalItems`

**Comment by rybesh** [comment]
OK, I will take care of this on Friday or Saturday.

**Comment by rybesh** [comment]
Where are you seeing this? Looks like I added these all to the context a while back (and the history file uses the same context as the dataset):

https://data.perio.do/context.json.html

**Comment by rybesh** [comment]
Note that the activitystreams namespace is a https URL (`https://www.w3.org/ns/activitystreams#`) and the canonical prefix is `as`: 

https://www.w3.org/ns/activitystreams#h-introduction

**Comment by ptgolden** [comment]
Huh! My local server doesn't compact them for whatever reason.

**Comment by rybesh** [comment]
Odd—are your rdflib versions the same as on the server?

rdflib==4.2.2
rdflib-jsonld==0.4.0
