### ISSUE TITLE
Marshaling patch requests is slow

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-server#124]
I'm updating going through the history of patch requests on the client, and I've noticed that the PatchList resource takes a looong time to marshal data for the response. I'm not familiar with the internals of flask_restful, so I couldn't say why.

e.g. When I request /patches?limit=100 from my local server, the request reliably takes 5-10 seconds. You can see this on the server too:

```
$ time curl -s https://data.perio.do/patches.json?limit=100 > /dev/null

real	0m10.265s
user	0m0.014s
sys	0m0.013s
```

Putting some timers in the code, it takes about .5s to do everything except marshal the data.

It's not crucially important, but it seems a bit off for this to take so long. As far as I can tell, this is the only place where we use `flask_restful.marshal` (besides individual patch request pages).

One thing we could do is publish the patch requests as a graph, like we do pretty much everything else. That graph could be cached whenever an update (new patch, merge, etc.) is made.

**Comment by ptgolden** [comment]
Fixed in 665abc5c13918549d36fdafe9ab95e23f3bf9d74

```
$ time curl -s https://data.staging.perio.do/patches.json?limit=100 > /dev/null

real	0m3.630s
user	0m0.023s
sys	0m0.027s
```

**Comment by ptgolden** [comment]
Sorry, didn't seem like it got deployed. Now actually fixed:

```
$ time curl -I -s https://data.staging.perio.do/patches.json?limit=100 > /dev/null

real	0m0.672s
user	0m0.016s
sys	0m0.009s
```

**Comment by rybesh** [comment]
Nice!
