### ISSUE TITLE
Email notifications for patch reviewers and submitters

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-server#154]
I wonder if it would be possible to generate email notifications to a) us/the eventual editorial board when a new patch is submitted and b) the submitter when a patch is merged or rejected. I found a bunch of new patches the last time I looked that had been submitted by our colleague in Argentina, but I wouldn't have seen them if I hadn't been checking -- and I've had to reject a couple for formatting issues, but now I have to figure out how to contact him to let him know that he needs to fix them. I realize that this might be more technical overhead than we want to manage, but it would certainly help smooth the workflow, especially as more people start putting things in.

**Comment by rybesh** [comment]
I notice that you had submitters in there too: note that we don't necessarily know the email addresses of submitters. But if we get RSS implemented we could show a message about how to subscribe to the updates feed.

**Comment by rybesh** [comment]
OK, we now have an Atom feed of recent activity:

https://data.perio.do/feed.xml

@atomrab I don't know if you use a feed reader, but if you do you can just add this feed. Here's what it looks like in Feedbin, the feed reader I use:

<img width="711" alt="Screen Shot 2020-05-08 at 3 04 06 PM" src="https://user-images.githubusercontent.com/84592/81440172-9827d000-913d-11ea-8484-d4e7f1829914.png">

If you want to notified when something happens, you could install a feed reader app on your phone and set up notifications.

Or there are services like IFTTT that can send you an email when a feed updates.

**Comment by ptgolden** [comment]
This is awesome
