### ISSUE TITLE
Period definition triples should include link to containing period collection

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-server#28]
JSON-LD for a single period definition (e.g. http://n2t.net/ark:/99152/p05krdxpb2m.jsonld) should include a `skos:inScheme` triple linking to the period collection of which it is a part. Right now they aren't there because we rely on JSON-LD containment to express this relation, but the container isn't there in the JSON-LD for a single definition.

**Comment by ptgolden** [comment]
Should this only be in the individual assertions and not in the main dataset?

**Comment by rybesh** [comment]
It is in the main dataset, it's just not in the JSON-LD for the individual period definitions, because we just "pluck out" the definition object from the larger dataset: https://github.com/periodo/periodo-server/blob/master/periodo.py#L491-L493

I can just do something similar to what I'm doing in `attach_to_dataset`, adding the triple on the fly:
https://github.com/periodo/periodo-server/blob/master/periodo.py#L298-L301

Not a high priority, just wanted to remind myself to do it later.

**Comment by ptgolden** [comment]
oh that makes sense- it's one of those places where we're using json-ld syntax magic?

**Comment by rybesh** [comment]
Addressed by #37
