### ISSUE TITLE
Caching dataset

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-server#42]
I'm not the world's greatest browser caching expert, @rybesh can you advise on this? We set the Last-modified header when returning the dataset, but not Cache-control or Expires headers. The result is that-- here's where I don't really know the rules-- the browser sets an expiration time itself, and the data is not revalidated on subsequent requests until that expiration time is met. I think this is the result of setting Last-modified without either of the other two.

Here's what we want:
  * The dataset shouldn't have to load on every request
  * When someone accepts a patch, it should be reflected in the canonical database immediately.

Would it make sense to return a 302 Found response for `/d/` to the current version of the dataset (ie `/d/?version=12`)?

**Comment by rybesh** [comment]
I think the "correct" solution is to use [ETags](https://en.wikipedia.org/wiki/HTTP_ETag). But 302 redirecting to the current version could be a simpler alternative.

**Comment by ptgolden** [comment]
I think I've got it. The issue wasn't a matching one (ETags would just be another implementation of that), it was that requests weren't being validated by browser requests. This was due to the fact that the browser was keeping requests cached until they expired. We weren't setting expiration or things like max-age headers, so the browser would do it itself according to some guess that it made.

I fixed the issue by setting the `Cache-control` header on the server to `max-age=0`, which requires caches to be revalidated on every request.

It's possible that we could only set `max-age=0` for users who are authenticated, and all others will get something longer (1 hour? 1 day?). However, this isn't necessary, and results in the same number of requests as if we used a redirect:

## Using redirects
  1. client -> /d/
  2. server -> 302 (Location /d/?version=12)
  3. client requests data first time; serves from cache the rest of the time since ?version=12 will never change

## Using mandatory revalidation
(first request)
  1. client -> /d/
  2. server -> 200 (Last-modified or ETag: xxx)

(subsequent requests)
  1. client -> /d/ (If-Modified-Since/If-None-Match)
  2. server -> 200 if modified else 304

---

The client will never know if there's new data, and new data is important in our context, so I think requiring revalidation for every request is OK.

**Comment by ptgolden** [comment]
Does this make sense? And does #43 look ok?

**Comment by ptgolden** [comment]
We could also store the last-modified time of the dataset in memory on the server so that 304 responses wouldn't even need to hit the database

**Comment by rybesh** [comment]
Yes, this makes sense. I would rather use ETags with version numbers than last-modified times, because they are more explicit. We went to the trouble of making sure versioning works; might as well take advantage of that.

**Comment by rybesh** [comment]
Also, we should probably use `no-cache` instead of `max-age=0` to force revalidation, as technically validation is only required by the former. But according to [this](http://stackoverflow.com/a/1383359) some browsers treat `no-cache` as a synonym for `no-store`, so maybe `max-age=0, must-revalidate, proxy-revalidate` is best.

**Comment by rybesh** [comment]
BTW this article is pretty good and clear: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching

**Comment by ptgolden** [comment]
ETag matching implemented in a9cd11b
