### ISSUE TITLE
Internet Archive "Save Page Now"?

### ISSUE THREAD

**Issue by ekansa** [periodo/periodo-server#5]
In cases where Period - Assertion sources don't have good linked data (say for some short-term Web source), perhaps we can use the Internet Archive's "Save Page Now" feature to archive the resource and get a persistent identifier that we can use for linked data purposes.

See: https://archive.org/web/

**Comment by rybesh** [comment]
This is more of a recommendation for contributors than a feature we need to develop, so I'm closing this.
