### ISSUE TITLE
Publish somewhere (PyPI?)

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-server#53]
It would be nice to have proper versioning and to be able to install with pip instead of the ad-hoc mess we've got right now.

Key thing would be to add a setup.py, and to have the database be in a configurable location.

**Comment by rybesh** [comment]
agree :100:%

**Comment by rybesh** [comment]
No longer convinced that this is worth doing since it wouldn't work correctly without HTTPs, and that is more easily set up using our Ansible deploy script.
