### ISSUE TITLE
Publish RSS feeds for changes

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-server#55]

**Comment by rybesh** [comment]
@ptgolden What do you think about changing our history JSON-LD to be valid [JSON Feed](https://jsonfeed.org/version/1)?

**Comment by rybesh** [comment]
Actually it might make more sense to have the list of patch requests be a feed, rather than the (extremely voluminous) full change history. This would make it easy to monitor for new patch submissions.

**Comment by rybesh** [comment]
duplicate of #154
