### ISSUE TITLE
N2T resolver now supports HTTPS

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-server#57]
It looks like N2T now supports HTTPs:

```
$ curl -D - https://n2t.net/ark:/99152/p0 -o /dev/null
Date: Thu, 01 Sep 2016 17:39:39 GMT
Server: Apache/2.2.29 (Unix) mod_ssl/2.2.29 OpenSSL/1.0.1k-fips DAV/2
Location: https://test.perio.do/
```

So we can start showing HTTPS permalinks everywhere, in theory... although it is unclear whether RDF-consuming libraries are treating the HTTP and HTTPS versions of URIs as the same or not.

[Note that N2T still does not support CORS.](https://github.com/periodo/periodo-server/issues/58)

**Comment by ekansa** [comment]
Just to complicate things on the https versus http thing, the mighty TBL himself has discussed the issue here: https://www.w3.org/DesignIssues/Security-NotTheS.html
