### ISSUE TITLE
N2T resolver does not set CORS headers

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-server#58]
So cross-domain HTTP requests to PeriodO URIs don't work.

**Comment by rybesh** [comment]
I will contact EZID about this.

**Comment by rybesh** [comment]
Submitted a new support request to EZID on 12/14/2017.

**Comment by rybesh** [comment]
Discussed this with EZID folks in early April 2018; they are working on a solution.

**Comment by ptgolden** [comment]
Should we check in again? It's pandemic time, but who knows

**Comment by rybesh** [comment]
Yeah, we should. On my TODO list

**Comment by rybesh** [comment]
Contacted John Kunze again on May 28, 2020. He replied:

> So sorry it's taken so long. We're still delayed on our Linux2 migration, which takes priority over CORS support.

**Comment by rybesh** [comment]
N2T now properly sets CORS headers.
