### ISSUE TITLE
Turtle rep uses wrong lang tags

### ISSUE THREAD

**Issue by VladimirAlexiev** [periodo/periodo-server#60]
Eg https://test.perio.do/#/p/Canonical/periodCollections/p07h9k6/?show_period=p07h9k6npwn
```turtle
    dcterms:language "spa-latn";
    skos:altLabel "Middle Palaeolithic"@eng-latn, "Paleolítico Medio"@spa-latn;

```

1. Should be `en` not `eng` and `es` not `spa`
2. `Latn` is the default script for these languages, so it is best omitted
3. It's best practice to spell the script capitalized (`Latn` instead of `latn`) though the treatment is equivalent
4. Since you use literal for `dcterms:language`, better use `dc:language` (DC Elements not DC Terms). Alternatively if you want to use DCterms, pick an appropriate URL from lingvo.org

**Comment by rybesh** [comment]
Thanks again for your feedback.

1–3 are duplicates of https://github.com/periodo/periodo-data/issues/30

What is the basis for 4? The documentation for `dcterms:language` states: 

> Recommended best practice is to use a controlled vocabulary such as RFC 4646 [e.g. language tag literals]

**Comment by VladimirAlexiev** [comment]
The idea is that DC props can have literal or resource values, whereas DCT have

**Comment by rybesh** [comment]
Moved to https://github.com/periodo/periodo-data/issues/42
