### ISSUE TITLE
JSONLD context to define namespaces used

### ISSUE THREAD

**Issue by VladimirAlexiev** [periodo/periodo-server#61]
Eg https://test.perio.do/#/p/Canonical/periodCollections/p07h9k6/?show_period=p07h9k6npwn
The JSONLD context at the end defines shortcut keys, eg
```js
    "start": "http://www.w3.org/2006/time#intervalStartedBy",
```
However, it does not define shortcuts for the namespaces used, eg
```js
    "time": "http://www.w3.org/2006/time#",
```
As a result, if you convert this JSONLD to Turtle, it doesn't use any prefixes  (except `periodo`).

Once you define the namespaces, it's better style to also use them in the context, eg
```js
    "start": "time:intervalStartedBy",
```

Finally, it's best practice to store the context at a defined URL and use it from there, instead of repeating it in every file you return.
Cheers!

**Comment by rybesh** [comment]
Thanks for your comments.

> As a result, if you convert this JSONLD to Turtle, it doesn't use any prefixes

That is not the case with all Turtle serializers, for example, the one we use to produce the Turtle output on our period collection pages (like the one you link to above; click the Turtle tab). What Turtle serializer are you using?

> Finally, it's best practice to store the context at a defined URL

There is not consensus on that point. In our case, we have decided that we do not want the ability to interpret PeriodO JSON as RDF to be dependent on network access.

**Comment by VladimirAlexiev** [comment]
```sh
riot --formatted=turtle p07h9k6npwn.jsonld
```
Does your Turtle serializer work from the JSONLD source?

**Comment by VladimirAlexiev** [comment]
> dependent on network access

The client will get the JSONLD data from your server, right? If he caches some data files, he may as well cache the context: http://json-ld.org/spec/latest/json-ld-api-best-practices/#cache-context.

If in the future you want to support several profiles (framing contexts) that the client can request by header, you can only do that if you use contexts by URL.

**Comment by rybesh** [comment]
Fixed by https://github.com/periodo/periodo-server/commit/b160b9e951368056131ece4156124445cba08fee
