### ISSUE TITLE
Rename collection -> authority and definition -> period

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-server#93]
some day when I have a lot of free time on my hands

**Comment by rybesh** [comment]
I guess that day was today.

[period] collection -> authority
[period] definition -> period

The following pull requests do the renaming in the `periodo-server`, `periodo-reconciler`, and `periodo.github.io` repos:
* https://github.com/periodo/periodo-server/pull/98
* https://github.com/periodo/periodo-reconciler/pull/17
* https://github.com/periodo/periodo.github.io/pull/4

There is also a  [script](https://github.com/periodo/periodo-validation/blob/master/fix/renaming.js#L21-L50) that creates a patch to do the renaming in the dataset.

I'm going to hold off on merging these until @ptgolden has signed off.

**Comment by ptgolden** [comment]
Can you create a gist of the actual jsonpatch that would be generated from that script?

**Comment by ptgolden** [comment]
Everything looks good to me; just wanted to see what it will look like

**Comment by rybesh** [comment]
https://gist.github.com/rybesh/8de52971e696d8f32c3f11240732b40d

**Comment by ptgolden** [comment]
Yep, this all looks great

**Comment by ptgolden** [comment]
Implemented in the client in https://github.com/periodo/periodo-client/pull/158

**Comment by rybesh** [comment]
OK, we now have a working version of the server with all the renaming-related patches running at https://migrating.perio.do/index.json.html. Can you npm publish a new version of the client so that `npm pack periodo-client@latest` will install it when we deploy? But maybe you want to test out the client with https://migrating.perio.do/d.json first.
