### ISSUE TITLE
Include patches in history

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-server#95]

**Comment by ptgolden** [comment]
In the JSON-LD response, we return the link to the JSON-Patch content of a patch with:

```
{
    "@id": "#patch-41",
    "url": "/ark:/99152/p0patches/41/patch.jsonpatch"
}
```

Where `url` is a `foaf:page`.

To embed the patch, we could use `cnt:ContentAsText`:

```
{
    "@id": "#patch-41",
    "@type": "cnt:ContentAsText",
    "cnt:chars": "[{\"op\": \"add\", ... }]",
    "dct:isFormatOf": { "@id" : "/ark:/99152/p0patches/41/patch.jsonpatch" },
    "dc:format": "application/json-patch+json"
}
```

It's a little silly to embed JSON within JSON-LD, but a JSON-Patch isn't RDF, so it makes sense.

Embedding all patches will result in a large response, but it should gzip down pretty small, and only require one additional SQL request.

**Comment by rybesh** [comment]
If I recall correctly, @ptgolden decided that this was not necessary after all.
