### ISSUE TITLE
Allow configuring namespace in history resource

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-server#96]
In provenance.py, we hardcode our ARK ids as the base URL for provenance resources. That returns misleading links when running a server that's not the one our ARK points to.

https://github.com/periodo/periodo-server/blob/89ba1210d47140c6e0090587d68d17b7b36142c7/periodo/provenance.py#L9-L12

**Comment by rybesh** [comment]
OK, I plan to take a similar approach to how I deal with the link to the JSON-LD context: https://github.com/periodo/periodo-server/blob/master/periodo/utils.py#L13-L17

**Comment by ptgolden** [comment]
Cool. I need this and #95 to continue working on viewing the history of Web backends. I'll work on the latter today.

**Comment by rybesh** [comment]
Commit 33edf44a5c5d75fbccca204fde2e7c7a99bfe549 makes it so URIs of changes, patches, etc. in the history are server-specific, unless the server is the canonical (production) one.
